server:
  port: 8185
  servlet:
    context-path: /elastic-query-web-client

elastic-query-web-client:
  elastic-query-service-host: localhost:8183
  webclient:
    connect-timeout-ms: 10000
    read-timeout-ms: 10000
    write-timeout-ms: 10000
    max-in-memory-size: 10485760 # 10MB
    content-type: 'application/vnd.api.v1+json'
    accept-type: 'application/vnd.api.v1+json'
    base-url: 'http://${elastic-query-web-client.elastic-query-service-host}/documents'
#    service-id: elastic-query-service
#    instances:
#      -
#        id: elastic-query-service-1
#        host: localhost
#        port: 8183
#      -
#        id: elastic-query-service-2
#        host: localhost
#        port: 8186
  query-by-text:
    method: POST
    uri: "/get-document-by-text"
    accept: ${elastic-query-web-client.webclient.accept-type}

spring:
  thymeleaf:
    cache: false #for DEV
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: 'elastic-query-web-client2'
            client-secret: '{cipher}c40f83e0938bfbd7246b5cf2054346b61bcad7994d676fc938934e01be8105a817a4e76a9f02de141926ec4bdabf208e075295e1e9b67a62c4191861b1ac4b03'
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid
        provider:
          keycloak:
            issuerUri: http://localhost:9091/auth/realms/sbmicroservices


security:
  logout-success-url: http://localhost:8185/elastic-query-web-client
  default-client-registration-id: keycloak
